name: CARE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
    - opencv-python
    - scikit-learn
    - seaborn
